### ISSUE TITLE
Unable to import or require local modules in the transformed parser

### ISSUE THREAD

**Issue by JayBerlin** [brainkim/babel-plugin-chevrotain-serialize#2]
When the file that contains your Parser class has import (or require) references to local modules, the require-from-string package is unable to find them.

For example,
```
import { Parser } from 'chevrotain';
import MyLocalTest from '../../MyLocalTest';
const Comma = chevrotain.createToken({
	name: "Comma",
	pattern: /,/
});

class MyParser extends chevrotain.Parser {
	constructor() {
		super({
			Comma
		});
		this.RULE("commas", () => {
			this.MANY(() => {
				this.CONSUME(Comma);
			});
		});
		this.performSelfAnalysis();
	}
}
```
The above errors with 
```
 Error: Cannot find module '../../test_modules/test'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
      at Function.Module._load (internal/modules/cjs/loader.js:506:25)
      at Module.require (internal/modules/cjs/loader.js:636:17)
      at require (internal/modules/cjs/helpers.js:20:18)
      at Object.<anonymous> (<anonymous>:10:36)
      at Module._compile (internal/modules/cjs/loader.js:688:30)
      at requireFromString (node_modules/require-from-string/index.js:28:4)
      at PluginPass.Program (src/index.js:165:48)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:193:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:88:12)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:118:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:90:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:146:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:94:17)
      at traverse (node_modules/@babel/traverse/lib/index.js:76:12)
      at transformFile (node_modules/@babel/core/lib/transformation/index.js:88:29)
      at runSync (node_modules/@babel/core/lib/transformation/index.js:45:3)
      at Object.transformFileSync (node_modules/@babel/core/lib/transform-file.js:82:38)
      at Context.<anonymous> (node_modules/babel-plugin-tester/dist/index.js:271:26)
```
The fix is pretty simple - add the filename into the requireFromString call:
```
const { [PARSERS_EXPORT_NAME]: parsers } = requireFromString(
	String(code),
	state.file.opts.filename
);
```

I would create a PR for this, however, the repo is currently using `chevrotain`  v3.7.4 and the Parser constructor super call API changed between v3 and v4, so all of the test fixtures need to be updated and I did not know if you wanted to do that with this plugin.  Let me know if you want me to update things across the board and I will create a PR and add a few additional tests for the above case.

**Comment by brainkim** [comment]
I’m happy to accept a PR! Personally I moved away from using chevrotain (I still highly recommend it) because I needed incremental lexing/parsing in my project and rolling my own lexer wasn’t too difficult. We should aim to match the latest version of chevrotain I think.

**Comment by JayBerlin** [comment]
I will take a look at what is involved in the changes.  There are a few other things that I have run into trying to have a Parser file that is not 'pure' and tries to import other modules that I am working thru now.

Thanks!

**Comment by JayBerlin** [comment]
PR created
https://github.com/brainkim/babel-plugin-chevrotain-serialize/pull/3

**Comment by JayBerlin** [comment]
Can you release these changes to NPM when you get a chance?  Thanks!
